development:
  storage: local
  path_prefix: tmp/files

test:
  storage: local
  path_prefix: tmp/files/test<%= ENV["PARALLEL_INDEX"] %>

## amazon storage example. requires valid amazon_s3.yml
production:
  storage: s3
