# This is currently used to tag errors from these paths in sentry
name: evaluate
owned_globs:
- app/controllers/anonymous_provisional_grades_controller.rb
- app/controllers/anonymous_submissions_controller.rb
- app/controllers/assignment_groups*_controller.rb
- app/controllers/assignment_overrides_controller.rb
- app/controllers/assignments*_controller.rb
- app/controllers/custom_gradebook_column*_controller.rb
- app/controllers/grade_change_audit_api_controller.rb
- app/controllers/grade_change_audit_api_controller.rb
- app/controllers/gradebook*_controller.rb
- app/controllers/grading_period*_controller.rb
- app/controllers/grading_schemes_json_controller.rb
- app/controllers/grading_standards*_controller.rb
- app/controllers/late_policy_controller.rb
- app/controllers/peer_reviews_api_controller.rb
- app/controllers/provisional_grades*_controller.rb
- app/controllers/rubric*_controller.rb
- app/controllers/submission*_controller.rb
- app/models/assessment_request.rb
- app/models/assignment/*
- app/models/assignments/*
- app/models/speed_grader/*
- app/models/anonymous_or_moderation_event.rb
- app/models/assignment.rb
- app/models/assignment_group.rb
- app/models/assignment_override.rb
- app/models/assignment_override_student.rb
- app/models/assignment_student_visibility.rb
- app/models/content_participation*
- app/models/custom_grade_status.rb
- app/models/custom_gradebook_column*
- app/models/gradebook*
- app/models/grading_period*
- app/models/grading_standard.rb
- app/models/late_policy.rb
- app/models/moderated_grading.rb
- app/models/moderation_grader.rb
- app/models/post_policy.rb
- app/models/rubric*
- app/models/score*
- app/models/standard_grade_status.rb
- app/models/submission*
- app/models/viewed_submission_comment.rb
