name: learning-foundations
owned_globs:
  - packages/canvas-rce/**/*
  - packages/canvas-media/**/*
  - lib/course_link_validator.rb
  - app/views/courses/link_validator.html.erb
  - ui/features/course_link_validator/**/*
  - ui/shared/immersive-reader/**/*
  - app/controllers/immersive_reader_controller.rb
  - app/models/wiki.rb
  - app/models/wiki_page.rb
  - app/models/wiki_page_lookup.rb
  - lib/api/v1/wiki_page.rb
  - ui/shared/wiki/**/*
  - ui/features/wiki_page_edit/**/*
  - ui/features/wiki_page_index/**/*
  - ui/features/wiki_page_revisions/**/*
  - ui/features/wiki_page_show/**/*
  - ui/features/wiki_page_view/**/*
  - app/views/wiki_pages/**/*
  - app/controllers/wiki_pages_controller.rb
  - app/controllers/wiki_pages_api_controller.rb
  - app/models/course_pace*
  - ui/features/course_paces/**/*
  - lib/course_pace*
  - app/controllers/course_pacing/**/*
  - app/controllers/course_paces_controller.rb
  - ui/features/syllabus/**/*
  - ui/shared/syllabus/**/*
  - app/views/assignments/syllabus.html.erb
  - app/models/content_share.rb
  - ui/shared/direct-sharing/**/*
  - app/controllers/calendar*
  - app/models/calendar_event.rb
  - lib/api/v1/account_calendar.rb
  - lib/api/v1/calendar_event.rb
  - ui/shared/calendar/**/*
  - ui/features/calendar/**/*
  - app/views/calendar_events/**/*
  - app/views/calendars/**/*
  - app/controllers/context_module*
  - app/models/context_module*
  - app/models/content_tag.rb
  - ui/shared/context-module-file-drop/**/*
  - ui/shared/context-modules/**/*
  - ui/shared/differentiated-modules/**/*
  - ui/shared/module-sequence-footer/**/*
  - ui/shared/modules/**/*
  - ui/features/context_module_progressions/**/*
  - ui/features/context_modules/**/*
  - ui/features/context_modules_publish_icon/**/*
  - ui/features/context_modules_publish_menu/**/*
  - ui/features/module_dnd/**/*
  - app/views/context_modules/**/*
